# Taller 1 Pandas Carlos Fernando Gonzalez Sarmiento

Base: https://www.kaggle.com/datasets/suraj520/car-sales-data

- Date: La fecha de la venta del coche
- Salesperson: El nombre del vendedor que realizó la venta
- Customer Name: El nombre del cliente que compró el coche
- Car Make: La marca del coche que se compró
- Car Model: El modelo del coche que se compró
- Car Year: El año del coche que se compró
- Sale Price: El precio de venta del coche en USD
- Commission Rate: La comisión pagada al vendedor en la venta
- Commission Earned: La cantidad de comisión que gana el vendedor en la venta

Antes de iniciar con el punto #1 quisiera cargarla y hacer una breve exploración de la base de datos

In [2]:
import pandas as pd

In [3]:
df_cars=pd.read_csv(r"C:\Users\piki_\Downloads\car_sales_data.csv")

In [5]:
df_cars.head()

,Date,Salesperson,Customer Name,Car Make,Car Model,Car Year,Sale Price,Commission Rate,Commission Earned
0,2022-08-01,Monica Moore MD,Mary Butler,Nissan,Altima,2018,15983,0.070495,1126.73
1,2023-03-15,Roberto Rose,Richard Pierce,Nissan,F-150,2016,38474,0.134439,5172.40
2,2023-04-29,Ashley Ramos,Sandra Moore,Ford,Civic,2016,33340,0.114536,3818.63
3,2022-09-04,Patrick Harris,Johnny Scott,Ford,Altima,2013,41937,0.092191,3866.20
4,2022-06-16,Eric Lopez,Vanessa Jones,Honda,Silverado,2022,20256,0.113490,2298.85

Al parecer la base pueda tener cierta incoherencia puesto que si vemos la fila #1 no tiene sentido que el coche siendo que la marca es Nissan, este sea "F-150" puesto que este vehiculo pertenece a la marca ford, entonces es una aclaración que podría servir para despues

In [6]:
df_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500000 entries, 0 to 2499999
Data columns (total 9 columns):
 #   Column             Dtype
---  ------             -----
 0   Date               object
 1   Salesperson        object
 2   Customer Name      object
 3   Car Make           object
 4   Car Model          object
 5   Car Year           int64
 6   Sale Price         int64
 7   Commission Rate    float64
 8   Commission Earned  float64
dtypes: float64(2), int64(2), object(5)
memory usage: 171.7+ MB

In [7]:
df_cars.describe()

           Car Year    Sale Price  Commission Rate  Commission Earned
count  2.500000e+06  2.500000e+06     2.500000e+06       2.500000e+06
mean   2.015996e+03  3.001218e+04     9.998766e-02       3.001005e+03
std    3.739132e+00  1.154514e+04     2.887202e-02       1.481467e+03
min    2.010000e+03  1.000000e+04     5.000014e-02       5.013400e+02
25%    2.013000e+03  2.001900e+04     7.496450e-02       1.821710e+03
50%    2.016000e+03  3.000600e+04     1.000058e-01       2.741910e+03
75%    2.019000e+03  4.002200e+04     1.250065e-01       3.978142e+03
max    2.022000e+03  5.000000e+04     1.500000e-01       7.494530e+03

## 1. Formula al menos 3 preguntas de análisis sobre tu conjunto de datos

1. ¿Cual fue la marca que mas se vendió historicamente en la base?
2. ¿Cual fue el modelo de auto que mas se vendió historicamente en la base?
3. ¿Cual fue el año que mas se vendieron autos?
4. ¿Quien fue el asesor o agente que mas comisión acumulada obtuvo historicamente en la base?
5. ¿Hubo alguien que tuvo mas de una compra de vehiculos historicamente?
6. ¿Cual fue el modelo de auto que mas se recaudó dinero historicamente en la base?
7. Cual fue la cantidad de dinero neto que se consiguó, es decir sale price - comisión de asesor

Se podrían realizar mas preguntas pero por el momento estas me parecen interesantes

## 2. Utilizando Pandas:
- Limpieza de datos (Pandas: dropna, fillna, replace, etc.)
- Filtrado y selección de datos
- Transformación de columnas, creación de variables nuevas
- Agrupaciones y resúmenes (groupby)

### - Limpieza de datos (Pandas: dropna, fillna, replace, etc.)

In [ ]:
df_cars.isna().sum()
# Inicialmente lo que podemos ver es que no existen valores faltantes en la base

Date                 0
Salesperson          0
Customer Name        0
Car Make             0
Car Model            0
Car Year             0
Sale Price           0
Commission Rate      0
Commission Earned    0
dtype: int64

In [ ]:
# Cuenta como limpieza convertir la columna Date a fecha puesto que arriba decia que era object y agregar una nueva columna con la
# con la fecha arreglada
df_cars['fecha_arr']=pd.to_datetime(df_cars['Date'],errors='coerce')
df_cars

,Date,Salesperson,Customer Name,Car Make,Car Model,Car Year,Sale Price,Commission Rate,Commission Earned,fecha_arr
0,2022-08-01,Monica Moore MD,Mary Butler,Nissan,Altima,2018,15983,0.070495,1126.73,2022-08-01
1,2023-03-15,Roberto Rose,Richard Pierce,Nissan,F-150,2016,38474,0.134439,5172.40,2023-03-15
2,2023-04-29,Ashley Ramos,Sandra Moore,Ford,Civic,2016,33340,0.114536,3818.63,2023-04-29
3,2022-09-04,Patrick Harris,Johnny Scott,Ford,Altima,2013,41937,0.092191,3866.20,2022-09-04
4,2022-06-16,Eric Lopez,Vanessa Jones,Honda,Silverado,2022,20256,0.113490,2298.85,2022-06-16
...,...,...,...,...,...,...,...,...,...,...
2499995,2022-05-26,Isabella Moore,Shirley Lee,Chevrolet,Silverado,2021,49823,0.062977,3137.70,2022-05-26
2499996,2022-10-03,Kimberly Snow,Tara Rodgers,Ford,F-150,2022,18803,0.068339,1284.97,2022-10-03
2499997,2022-06-07,Jessica Young,Jennifer Moore,Chevrolet,Civic,2010,30863,0.088915,2744.19,2022-06-07
2499998,2023-02-15,Donald Barber,Ashley Diaz,Honda,Silverado,2014,26125,0.088260,2305.80,2023-02-15
2499999,2023-03-24,Kayla Fowler,Nathan Thompson,Honda,Civic,2010,20762,0.137105,2846.57,2023-03-24

In [ ]:
df_cars.info()
#Vemos que ya quedó

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500000 entries, 0 to 2499999
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   Date               object
 1   Salesperson        object
 2   Customer Name      object
 3   Car Make           object
 4   Car Model          object
 5   Car Year           int64
 6   Sale Price         int64
 7   Commission Rate    float64
 8   Commission Earned  float64
 9   fecha_arr          datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 190.7+ MB

In [ ]:
#Miremos duplicados
df_cars.duplicated().sum()
# No hay duplicados

np.int64(0)

In [ ]:
#Finalmente identifiquemos incongruencias
df_cars[df_cars['Sale Price']<=0]
#No hay ningun carro vendido por un precio menor o igual a cero

Empty DataFrame
Columns: [Date, Salesperson, Customer Name, Car Make, Car Model, Car Year, Sale Price, Commission Rate, Commission Earned, fecha_arr]
Index: []

### - Filtrado y selección de datos

In [ ]:
df_cars.shape
# Existen 2'500.000 autos vendidos

(2500000, 10)

In [36]:
sum(df_cars['Sale Price'])
#Se consiguión un monto historico de la base de 75.030.446.855 dolares

75030446855

In [ ]:
# Ahora basandonos en las preguntas que debemos responder
# Marca que mas se vendio historicamente en la base

df_cars.groupby('Car Make')['Car Model'].count().sort_values(ascending=False)

# La marca que mas se vendio fue Honda

Car Make
Honda        500687
Chevrolet    500455
Toyota       500147
Ford         499781
Nissan       498930
Name: Car Model, dtype: int64

In [ ]:
# Modelo que mas se vendio historicamente en la base

df_cars.groupby('Car Model')['Car Make'].count().sort_values(ascending=False)

# La modelo que mas se vendio fue Silverado

Car Model
Silverado    500842
Civic        500498
Corolla      500162
F-150        499679
Altima       498819
Name: Car Make, dtype: int64

In [ ]:
# Año que mas se vendieron autos
df_cars['fecha_ano']=df_cars['fecha_arr'].dt.year
df_cars

,Date,Salesperson,Customer Name,Car Make,Car Model,Car Year,Sale Price,Commission Rate,Commission Earned,fecha_arr,fecha_ano
0,2022-08-01,Monica Moore MD,Mary Butler,Nissan,Altima,2018,15983,0.070495,1126.73,2022-08-01,2022
1,2023-03-15,Roberto Rose,Richard Pierce,Nissan,F-150,2016,38474,0.134439,5172.40,2023-03-15,2023
2,2023-04-29,Ashley Ramos,Sandra Moore,Ford,Civic,2016,33340,0.114536,3818.63,2023-04-29,2023
3,2022-09-04,Patrick Harris,Johnny Scott,Ford,Altima,2013,41937,0.092191,3866.20,2022-09-04,2022
4,2022-06-16,Eric Lopez,Vanessa Jones,Honda,Silverado,2022,20256,0.113490,2298.85,2022-06-16,2022
...,...,...,...,...,...,...,...,...,...,...,...
2499995,2022-05-26,Isabella Moore,Shirley Lee,Chevrolet,Silverado,2021,49823,0.062977,3137.70,2022-05-26,2022
2499996,2022-10-03,Kimberly Snow,Tara Rodgers,Ford,F-150,2022,18803,0.068339,1284.97,2022-10-03,2022
2499997,2022-06-07,Jessica Young,Jennifer Moore,Chevrolet,Civic,2010,30863,0.088915,2744.19,2022-06-07,2022
2499998,2023-02-15,Donald Barber,Ashley Diaz,Honda,Silverado,2014,26125,0.088260,2305.80,2023-02-15,2023
2499999,2023-03-24,Kayla Fowler,Nathan Thompson,Honda,Civic,2010,20762,0.137105,2846.57,2023-03-24,2023

In [ ]:
df_cars.groupby('fecha_ano')['Car Make'].count().sort_values(ascending=False)
# Año que mas se vendieron autos 2022

fecha_ano
2022    1674502
2023     825498
Name: Car Make, dtype: int64

In [ ]:
# Asesor o agente que mas comisión obtuvo
df_cars.groupby('Salesperson')['Commission Earned'].sum().sort_values(ascending=False)
# Michael Smith fue el asesor que mas comisión obtuvo 3.658.467 dolares

Salesperson
Michael Smith         3658467.56
Michael Johnson       2883629.29
David Smith           2456566.33
James Smith           2448405.59
Robert Smith          2275950.52
                         ...
Christy Pennington        510.12
Cheryl Erickson           508.91
Mr. Joseph Garrett        508.32
Felicia Mcneil            506.50
James Rogers DDS          503.33
Name: Commission Earned, Length: 518657, dtype: float64

In [ ]:
# Hubo alguien que tuvo mas de una compra de vehiculos historicamente?
# Esta se puede resolver de varias formas pero lo haré con otro group by
df_cars.groupby('Customer Name')['Salesperson'].count().sort_values(ascending=False)
# En este caso si, hubieron varios clientes con mas de una compra

Customer Name
Michael Smith      1167
Michael Johnson     889
David Smith         796
James Smith         789
Jennifer Smith      787
                   ...
Zoe Summers           1
Zoe Strickland        1
Zoe Stewart           1
Zoe Stevenson         1
Zoe Steele            1
Name: Salesperson, Length: 518251, dtype: int64

In [ ]:
conteo_vendedores= df_cars.groupby('Customer Name')['Salesperson'].count().sort_values(ascending=False)
mas1 = conteo_vendedores[conteo_vendedores > 1].count()

print(mas1)
# En total hay 283725 clientes que hicieron mas de una compra

283725

In [ ]:
# Modelo de auto que mas recaudó dinero historicamente
df_cars.groupby('Car Model')['Sale Price'].sum().sort_values(ascending=False)
#Fue en este caso la silverado con 15.040.374.937 dolares

Car Model
Silverado    15040374937
Corolla      15016772687
Civic        15009604790
F-150        14988132564
Altima       14975561877
Name: Sale Price, dtype: int64

In [55]:
#Cantidad de dinero neto sale price - comisión asesor
df_cars['Dinero neto']=df_cars['Sale Price']-df_cars['Commission Earned']
df_cars

,Date,Salesperson,Customer Name,Car Make,Car Model,Car Year,Sale Price,Commission Rate,Commission Earned,fecha_arr,fecha_ano,Dinero neto
0,2022-08-01,Monica Moore MD,Mary Butler,Nissan,Altima,2018,15983,0.070495,1126.73,2022-08-01,2022,14856.27
1,2023-03-15,Roberto Rose,Richard Pierce,Nissan,F-150,2016,38474,0.134439,5172.40,2023-03-15,2023,33301.60
2,2023-04-29,Ashley Ramos,Sandra Moore,Ford,Civic,2016,33340,0.114536,3818.63,2023-04-29,2023,29521.37
3,2022-09-04,Patrick Harris,Johnny Scott,Ford,Altima,2013,41937,0.092191,3866.20,2022-09-04,2022,38070.80
4,2022-06-16,Eric Lopez,Vanessa Jones,Honda,Silverado,2022,20256,0.113490,2298.85,2022-06-16,2022,17957.15
...,...,...,...,...,...,...,...,...,...,...,...,...
2499995,2022-05-26,Isabella Moore,Shirley Lee,Chevrolet,Silverado,2021,49823,0.062977,3137.70,2022-05-26,2022,46685.30
2499996,2022-10-03,Kimberly Snow,Tara Rodgers,Ford,F-150,2022,18803,0.068339,1284.97,2022-10-03,2022,17518.03
2499997,2022-06-07,Jessica Young,Jennifer Moore,Chevrolet,Civic,2010,30863,0.088915,2744.19,2022-06-07,2022,28118.81
2499998,2023-02-15,Donald Barber,Ashley Diaz,Honda,Silverado,2014,26125,0.088260,2305.80,2023-02-15,2023,23819.20
2499999,2023-03-24,Kayla Fowler,Nathan Thompson,Honda,Civic,2010,20762,0.137105,2846.57,2023-03-24,2023,17915.43

In [ ]:
sum(df_cars['Dinero neto'])
# Ganancia neta

67527933512.840485

In [69]:
a=df_cars.groupby('Car Model')['Sale Price'].sum().sort_values(ascending=False).iloc[1]
b=sum(df_cars['Sale Price'])
a/b*100

np.float64(20.014238641042144)

## 3. Responde las preguntas planteadas con una breve interpretación.

#### 1. ¿Cual fue la marca que mas se vendió historicamente en la base?

A partir de la línea de código #38 el resultado que dio fue que Honda fue la marca que mas vendió autos con un total de 500.687 carros, se podría decir que es la marca que mas prefieren los clientes

#### 2. ¿Cual fue el modelo de auto que mas se vendió historicamente en la base?

A partir de la línea de código #39 el resultado que dio fue que el modelo de Silverado fue el modelo que mas vendió autos con un total de 500.842 carros podría decir que es el modelo que mas prefieren los clientes

#### 3. ¿Cual fue el año que mas se vendieron autos?

A partir de la línea de código #44 el resultado que dio fue que el año que mas se vendieron autos fue en el 2022 con un total de 1.674.502 ventas de autos

#### 4. ¿Quien fue el asesor o agente que mas comisión acumulada obtuvo historicamente en la base?

A partir de la línea de código #46 el resultado que dio fue que el asesor que mas comisión acumulada obtuvo, fue Michael Smith con un monto total de 3.658.467,56 dolares

#### 5. ¿Hubo alguien que tuvo mas de una compra de vehiculos historicamente?

Si, hubieron 283.725 clientes que compraron mas de una vez 

#### 6. ¿Cual fue el modelo de auto que mas se recaudó dinero historicamente en la base?

A partir de la línea de código #54 el resultado que dio fue que el recaudo o suma total de dinero obtenida para el modelo que mas recaudo fue la Silverado con 15.040.374.937 dolares

#### 7. Cual fue la cantidad de dinero neto que se consiguó, es decir sale price - comisión de asesor

Basandonos en la linea 55 vemos que luego de hacer la resta de sale price que es precio de venta - Commission Earned comisión ganada para el asesor nos da un total de 67.527.933.512,840485 dolares

Dato interesante la silverado representa el 20,01% aproximadamente de la suma de Sale Price o precio de venta