# Taller 3 APIs y Power BI Carlos Fernando Gonzalez Sarmiento

API: https://archive-api.open-meteo.com

#### Conexión al API

In [25]:
import requests

base_url = "https://archive-api.open-meteo.com"
endpoint = "/v1/archive"

parametros = {
    "latitude": 4.7110, #Estas cordenadas son las de Bogota
    "longitude": -74.0721, #Estas cordenadas son las de Bogota
    "start_date": "2024-01-01",
    "end_date": "2025-12-31", #Ejemplo de 2024 a 2025
    "daily": [
        "temperature_2m_max",
        "temperature_2m_min",
        "temperature_2m_mean",
        "precipitation_sum",
        "wind_speed_10m_max",
        "weather_code"
    ],
    "timezone": "America/Bogota" #Que me lo traiga con la zona horaria de Bogota
}

response1 = requests.get(
    base_url + endpoint,
    params=parametros
)

if response1.status_code == 200:
    print(
        "Conexión exitosa a la API. Código de estado:",
        response1.status_code
    )
else:
    print(
        "Conexión fallida a la API. Código de estado:",
        response1.status_code
    )

Conexión exitosa a la API. Código de estado: 200

In [26]:
datos_json = response1.json()

datos_json["daily"]

{'time': ['2024-01-01',
  '2024-01-02',
  '2024-01-03',
  '2024-01-04',
  '2024-01-05',
  '2024-01-06',
  '2024-01-07',
  '2024-01-08',
  '2024-01-09',
  '2024-01-10',
  '2024-01-11',
  '2024-01-12',
  '2024-01-13',
  '2024-01-14',
  '2024-01-15',
  '2024-01-16',
  '2024-01-17',
  '2024-01-18',
  '2024-01-19',
  '2024-01-20',
  '2024-01-21',
  '2024-01-22',
  '2024-01-23',
  '2024-01-24',
  '2024-01-25',
  '2024-01-26',
  '2024-01-27',
  '2024-01-28',
  '2024-01-29',
  '2024-01-30',
  '2024-01-31',
  '2024-02-01',
  '2024-02-02',
  '2024-02-03',
  '2024-02-04',
  '2024-02-05',
  '2024-02-06',
  '2024-02-07',
  '2024-02-08',
  '2024-02-09',
  '2024-02-10',
  '2024-02-11',
  '2024-02-12',
  '2024-02-13',
  '2024-02-14',
  '2024-02-15',
  '2024-02-16',
  '2024-02-17',
  '2024-02-18',
  '2024-02-19',
  '2024-02-20',
  '2024-02-21',
  '2024-02-22',
  '2024-02-23',
  '2024-02-24',
  '2024-02-25',
  '2024-02-26',
  '2024-02-27',
  '2024-02-28',
  '2024-02-29',
  '2024-03-01',
  '2024-03-02',
  '2024-03-03',
  '2024-03-04',
  '2024-03-05',
  '2024-03-06',
  '2024-03-07',
  '2024-03-08',
  '2024-03-09',
  '2024-03-10',
  '2024-03-11',
  '2024-03-12',
  '2024-03-13',
  '2024-03-14',
  '2024-03-15',
  '2024-03-16',
  '2024-03-17',
  '2024-03-18',
  '2024-03-19',
  '2024-03-20',
  '2024-03-21',
  '2024-03-22',
  '2024-03-23',
  '2024-03-24',
  '2024-03-25',
  '2024-03-26',
  '2024-03-27',
  '2024-03-28',
  '2024-03-29',
  '2024-03-30',
  '2024-03-31',
  '2024-04-01',
  '2024-04-02',
  '2024-04-03',
  '2024-04-04',
  '2024-04-05',
  '2024-04-06',
  '2024-04-07',
  '2024-04-08',
  '2024-04-09',
  '2024-04-10',
  '2024-04-11',
  '2024-04-12',
  '2024-04-13',
  '2024-04-14',
  '2024-04-15',
  '2024-04-16',
  '2024-04-17',
  '2024-04-18',
  '2024-04-19',
  '2024-04-20',
  '2024-04-21',
  '2024-04-22',
  '2024-04-23',
  '2024-04-24',
  '2024-04-25',
  '2024-04-26',
  '2024-04-27',
  '2024-04-28',
  '2024-04-29',
  '2024-04-30',
  '2024-05-01',
  '2024-05-02',
  '2024-05-03',
  '2024-05-04',
  '2024-05-05',
  '2024-05-06',
  '2024-05-07',
  '2024-05-08',
  '2024-05-09',
  '2024-05-10',
  '2024-05-11',
  '2024-05-12',
  '2024-05-13',
  '2024-05-14',
  '2024-05-15',
  '2024-05-16',
  '2024-05-17',
  '2024-05-18',
  '2024-05-19',
  '2024-05-20',
  '2024-05-21',
  '2024-05-22',
  '2024-05-23',
  '2024-05-24',
  '2024-05-25',
  '2024-05-26',
  '2024-05-27',
  '2024-05-28',
  '2024-05-29',
  '2024-05-30',
  '2024-05-31',
  '2024-06-01',
  '2024-06-02',
  '2024-06-03',
  '2024-06-04',
  '2024-06-05',
  '2024-06-06',
  '2024-06-07',
  '2024-06-08',
  '2024-06-09',
  '2024-06-10',
  '2024-06-11',
  '2024-06-12',
  '2024-06-13',
  '2024-06-14',
  '2024-06-15',
  '2024-06-16',
  '2024-06-17',
  '2024-06-18',
  '2024-06-19',
  '2024-06-20',
  '2024-06-21',
  '2024-06-22',
  '2024-06-23',
  '2024-06-24',
  '2024-06-25',
  '2024-06-26',
  '2024-06-27',
  '2024-06-28',
  '2024-06-29',
  '2024-06-30',
  '2024-07-01',
  '2024-07-02',
  '2024-07-03',
  '2024-07-04',
  '2024-07-05',
  '2024-07-06',
  '2024-07-07',
  '2024-07-08',
  '2024-07-09',
  '2024-07-10',
  '2024-07-11',
  '2024-07-12',
  '2024-07-13',
  '2024-07-14',
  '2024-07-15',
  '2024-07-16',
  '2024-07-17',
  '2024-07-18',
  '2024-07-19',
  '2024-07-20',
  '2024-07-21',
  '2024-07-22',
  '2024-07-23',
  '2024-07-24',
  '2024-07-25',
  '2024-07-26',
  '2024-07-27',
  '2024-07-28',
  '2024-07-29',
  '2024-07-30',
  '2024-07-31',
  '2024-08-01',
  '2024-08-02',
  '2024-08-03',
  '2024-08-04',
  '2024-08-05',
  '2024-08-06',
  '2024-08-07',
  '2024-08-08',
  '2024-08-09',
  '2024-08-10',
  '2024-08-11',
  '2024-08-12',
  '2024-08-13',
  '2024-08-14',
  '2024-08-15',
  '2024-08-16',
  '2024-08-17',
  '2024-08-18',
  '2024-08-19',
  '2024-08-20',
  '2024-08-21',
  '2024-08-22',
  '2024-08-23',
  '2024-08-24',
  '2024-08-25',
  '2024-08-26',
  '2024-08-27',
  '2024-08-28',
  '2024-08-29',
  '2024-08-30',
  '2024-08-31',
  '2024-09-01',
  '2024-09-02',
  '2024-09-03',
  '2024-09-04',
  '2024-09-05',
  '2024-09-06',
  '2024-09-07',
  '2024-09-08',
  '2024-09-09',
  '2024-09-10',
  '2024-09-11',
  '2024-09-12',
  '2024-09-13',
  '2024-09-14',
  '2024-09-15',
  '2024-09-16',
  '2024-09-17',
  '2024-09-18',
  '2024-09-19',
  '2024-09-20',
  '2024-09-21',
  '2024-09-22',
  '2024-09-23',
  '2024-09-24',
  '2024-09-25',
  '2024-09-26',
  '2024-09-27',
  '2024-09-28',
  '2024-09-29',
  '2024-09-30',
  '2024-10-01',
  '2024-10-02',
  '2024-10-03',
  '2024-10-04',
  '2024-10-05',
  '2024-10-06',
  '2024-10-07',
  '2024-10-08',
  '2024-10-09',
  '2024-10-10',
  '2024-10-11',
  '2024-10-12',
  '2024-10-13',
  '2024-10-14',
  '2024-10-15',
  '2024-10-16',
  '2024-10-17',
  '2024-10-18',
  '2024-10-19',
  '2024-10-20',
  '2024-10-21',
  '2024-10-22',
  '2024-10-23',
  '2024-10-24',
  '2024-10-25',
  '2024-10-26',
  '2024-10-27',
  '2024-10-28',
  '2024-10-29',
  '2024-10-30',
  '2024-10-31',
  '2024-11-01',
  '2024-11-02',
  '2024-11-03',
  '2024-11-04',
  '2024-11-05',
  '2024-11-06',
  '2024-11-07',
  '2024-11-08',
  '2024-11-09',
  '2024-11-10',
  '2024-11-11',
  '2024-11-12',
  '2024-11-13',
  '2024-11-14',
  '2024-11-15',
  '2024-11-16',
  '2024-11-17',
  '2024-11-18',
  '2024-11-19',
  '2024-11-20',
  '2024-11-21',
  '2024-11-22',
  '2024-11-23',
  '2024-11-24',
  '2024-11-25',
  '2024-11-26',
  '2024-11-27',
  '2024-11-28',
  '2024-11-29',
  '2024-11-30',
  '2024-12-01',
  '2024-12-02',
  '2024-12-03',
  '2024-12-04',
  '2024-12-05',
  '2024-12-06',
  '2024-12-07',
  '2024-12-08',
  '2024-12-09',
  '2024-12-10',
  '2024-12-11',
  '2024-12-12',
  '2024-12-13',
  '2024-12-14',
  '2024-12-15',
  '2024-12-16',
  '2024-12-17',
  '2024-12-18',
  '2024-12-19',
  '2024-12-20',
  '2024-12-21',
  '2024-12-22',
  '2024-12-23',
  '2024-12-24',
  '2024-12-25',
  '2024-12-26',
  '2024-12-27',
  '2024-12-28',
  '2024-12-29',
  '2024-12-30',
  '2024-12-31',
  '2025-01-01',
  '2025-01-02',
  '2025-01-03',
  '2025-01-04',
  '2025-01-05',
  '2025-01-06',
  '2025-01-07',
  '2025-01-08',
  '2025-01-09',
  '2025-01-10',
  '2025-01-11',
  '2025-01-12',
  '2025-01-13',
  '2025-01-14',
  '2025-01-15',
  '2025-01-16',
  '2025-01-17',
  '2025-01-18',
  '2025-01-19',
  '2025-01-20',
  '2025-01-21',
  '2025-01-22',
  '2025-01-23',
  '2025-01-24',
  '2025-01-25',
  '2025-01-26',
  '2025-01-27',
  '2025-01-28',
  '2025-01-29',
  '2025-01-30',
  '2025-01-31',
  '2025-02-01',
  '2025-02-02',
  '2025-02-03',
  '2025-02-04',
  '2025-02-05',
  '2025-02-06',
  '2025-02-07',
  '2025-02-08',
  '2025-02-09',
  '2025-02-10',
  '2025-02-11',
  '2025-02-12',
  '2025-02-13',
  '2025-02-14',
  '2025-02-15',
  '2025-02-16',
  '2025-02-17',
  '2025-02-18',
  '2025-02-19',
  '2025-02-20',
  '2025-02-21',
  '2025-02-22',
  '2025-02-23',
  '2025-02-24',
  '2025-02-25',
  '2025-02-26',
  '2025-02-27',
  '2025-02-28',
  '2025-03-01',
  '2025-03-02',
  '2025-03-03',
  '2025-03-04',
  '2025-03-05',
  '2025-03-06',
  '2025-03-07',
  '2025-03-08',
  '2025-03-09',
  '2025-03-10',
  '2025-03-11',
  '2025-03-12',
  '2025-03-13',
  '2025-03-14',
  '2025-03-15',
  '2025-03-16',
  '2025-03-17',
  '2025-03-18',
  '2025-03-19',
  '2025-03-20',
  '2025-03-21',
  '2025-03-22',
  '2025-03-23',
  '2025-03-24',
  '2025-03-25',
  '2025-03-26',
  '2025-03-27',
  '2025-03-28',
  '2025-03-29',
  '2025-03-30',
  '2025-03-31',
  '2025-04-01',
  '2025-04-02',
  '2025-04-03',
  '2025-04-04',
  '2025-04-05',
  '2025-04-06',
  '2025-04-07',
  '2025-04-08',
  '2025-04-09',
  '2025-04-10',
  '2025-04-11',
  '2025-04-12',
  '2025-04-13',
  '2025-04-14',
  '2025-04-15',
  '2025-04-16',
  '2025-04-17',
  '2025-04-18',
  '2025-04-19',
  '2025-04-20',
  '2025-04-21',
  '2025-04-22',
  '2025-04-23',
  '2025-04-24',
  '2025-04-25',
  '2025-04-26',
  '2025-04-27',
  '2025-04-28',
  '2025-04-29',
  '2025-04-30',
  '2025-05-01',
  '2025-05-02',
  '2025-05-03',
  '2025-05-04',
  '2025-05-05',
  '2025-05-06',
  '2025-05-07',
  '2025-05-08',
  '2025-05-09',
  '2025-05-10',
  '2025-05-11',
  '2025-05-12',
  '2025-05-13',
  '2025-05-14',
  '2025-05-15',
  '2025-05-16',
  '2025-05-17',
  '2025-05-18',
  '2025-05-19',
  '2025-05-20',
  '2025-05-21',
  '2025-05-22',
  '2025-05-23',
  '2025-05-24',
  '2025-05-25',
  '2025-05-26',
  '2025-05-27',
  '2025-05-28',
  '2025-05-29',
  '2025-05-30',
  '2025-05-31',
  '2025-06-01',
  '2025-06-02',
  '2025-06-03',
  '2025-06-04',
  '2025-06-05',
  '2025-06-06',
  '2025-06-07',
  '2025-06-08',
  '2025-06-09',
  '2025-06-10',
  '2025-06-11',
  '2025-06-12',
  '2025-06-13',
  '2025-06-14',
  '2025-06-15',
  '2025-06-16',
  '2025-06-17',
  '2025-06-18',
  '2025-06-19',
  '2025-06-20',
  '2025-06-21',
  '2025-06-22',
  '2025-06-23',
  '2025-06-24',
  '2025-06-25',
  '2025-06-26',
  '2025-06-27',
  '2025-06-28',
  '2025-06-29',
  '2025-06-30',
  '2025-07-01',
  '2025-07-02',
  '2025-07-03',
  '2025-07-04',
  '2025-07-05',
  '2025-07-06',
  '2025-07-07',
  '2025-07-08',
  '2025-07-09',
  '2025-07-10',
  '2025-07-11',
  '2025-07-12',
  '2025-07-13',
  '2025-07-14',
  '2025-07-15',
  '2025-07-16',
  '2025-07-17',
  '2025-07-18',
  '2025-07-19',
  '2025-07-20',
  '2025-07-21',
  '2025-07-22',
  '2025-07-23',
  '2025-07-24',
  '2025-07-25',
  '2025-07-26',
  '2025-07-27',
  '2025-07-28',
  '2025-07-29',
  '2025-07-30',
  '2025-07-31',
  '2025-08-01',
  '2025-08-02',
  '2025-08-03',
  '2025-08-04',
  '2025-08-05',
  '2025-08-06',
  '2025-08-07',
  '2025-08-08',
  '2025-08-09',
  '2025-08-10',
  '2025-08-11',
  '2025-08-12',
  '2025-08-13',
  '2025-08-14',
  '2025-08-15',
  '2025-08-16',
  '2025-08-17',
  '2025-08-18',
  '2025-08-19',
  '2025-08-20',
  '2025-08-21',
  '2025-08-22',
  '2025-08-23',
  '2025-08-24',
  '2025-08-25',
  '2025-08-26',
  '2025-08-27',
  '2025-08-28',
  '2025-08-29',
  '2025-08-30',
  '2025-08-31',
  '2025-09-01',
  '2025-09-02',
  '2025-09-03',
  '2025-09-04',
  '2025-09-05',
  '2025-09-06',
  '2025-09-07',
  '2025-09-08',
  '2025-09-09',
  '2025-09-10',
  '2025-09-11',
  '2025-09-12',
  '2025-09-13',
  '2025-09-14',
  '2025-09-15',
  '2025-09-16',
  '2025-09-17',
  '2025-09-18',
  '2025-09-19',
  '2025-09-20',
  '2025-09-21',
  '2025-09-22',
  '2025-09-23',
  '2025-09-24',
  '2025-09-25',
  '2025-09-26',
  '2025-09-27',
  '2025-09-28',
  '2025-09-29',
  '2025-09-30',
  '2025-10-01',
  '2025-10-02',
  '2025-10-03',
  '2025-10-04',
  '2025-10-05',
  '2025-10-06',
  '2025-10-07',
  '2025-10-08',
  '2025-10-09',
  '2025-10-10',
  '2025-10-11',
  '2025-10-12',
  '2025-10-13',
  '2025-10-14',
  '2025-10-15',
  '2025-10-16',
  '2025-10-17',
  '2025-10-18',
  '2025-10-19',
  '2025-10-20',
  '2025-10-21',
  '2025-10-22',
  '2025-10-23',
  '2025-10-24',
  '2025-10-25',
  '2025-10-26',
  '2025-10-27',
  '2025-10-28',
  '2025-10-29',
  '2025-10-30',
  '2025-10-31',
  '2025-11-01',
  '2025-11-02',
  '2025-11-03',
  '2025-11-04',
  '2025-11-05',
  '2025-11-06',
  '2025-11-07',
  '2025-11-08',
  '2025-11-09',
  '2025-11-10',
  '2025-11-11',
  '2025-11-12',
  '2025-11-13',
  '2025-11-14',
  '2025-11-15',
  '2025-11-16',
  '2025-11-17',
  '2025-11-18',
  '2025-11-19',
  '2025-11-20',
  '2025-11-21',
  '2025-11-22',
  '2025-11-23',
  '2025-11-24',
  '2025-11-25',
  '2025-11-26',
  '2025-11-27',
  '2025-11-28',
  '2025-11-29',
  '2025-11-30',
  '2025-12-01',
  '2025-12-02',
  '2025-12-03',
  '2025-12-04',
  '2025-12-05',
  '2025-12-06',
  '2025-12-07',
  '2025-12-08',
  '2025-12-09',
  '2025-12-10',
  '2025-12-11',
  '2025-12-12',
  '2025-12-13',
  '2025-12-14',
  '2025-12-15',
  '2025-12-16',
  '2025-12-17',
  '2025-12-18',
  '2025-12-19',
  '2025-12-20',
  '2025-12-21',
  '2025-12-22',
  '2025-12-23',
  '2025-12-24',
  '2025-12-25',
  '2025-12-26',
  '2025-12-27',
  '2025-12-28',
  '2025-12-29',
  '2025-12-30',
  '2025-12-31'],
 'temperature_2m_max': [21.4,
  22.1,
  22.0,
  21.9,
  21.4,
  22.5,
  20.7,
  21.8,
  21.8,
  22.8,
  23.5,
  22.3,
  20.7,
  22.5,
  22.9,
  21.5,
  22.8,
  23.4,
  22.3,
  22.4,
  21.2,
  23.3,
  23.1,
  24.6,
  26.1,
  24.6,
  24.8,
  25.0,
  24.7,
  24.7,
  23.9,
  23.1,
  21.0,
  21.8,
  20.7,
  19.3,
  20.4,
  21.9,
  22.1,
  22.3,
  21.5,
  22.5,
  23.8,
  24.3,
  20.7,
  21.7,
  20.7,
  20.4,
  23.2,
  24.8,
  24.1,
  22.6,
  22.4,
  24.3,
  22.1,
  22.0,
  23.8,
  21.9,
  22.4,
  23.9,
  23.3,
  23.7,
  21.7,
  22.0,
  22.3,
  23.8,
  22.7,
  22.2,
  21.7,
  22.7,
  22.2,
  22.5,
  21.9,
  21.4,
  23.6,
  22.6,
  22.9,
  23.0,
  23.0,
  25.3,
  20.8,
  26.2,
  24.0,
  23.6,
  22.7,
  21.6,
  21.7,
  22.1,
  20.0,
  21.4,
  20.7,
  22.2,
  21.5,
  20.3,
  21.4,
  22.0,
  21.3,
  22.0,
  20.8,
  22.1,
  22.9,
  25.5,
  24.4,
  23.1,
  24.3,
  24.0,
  24.2,
  25.0,
  21.4,
  20.5,
  22.0,
  19.3,
  16.4,
  20.9,
  21.8,
  20.9,
  21.9,
  20.6,
  20.0,
  17.8,
  21.7,
  20.2,
  21.3,
  20.5,
  21.0,
  19.8,
  21.1,
  22.2,
  21.6,
  18.7,
  20.2,
  22.3,
  19.7,
  22.1,
  21.6,
  20.9,
  20.7,
  20.8,
  21.4,
  20.4,
  19.6,
  20.0,
  19.9,
  21.6,
  22.4,
  19.4,
  19.8,
  20.0,
  21.3,
  18.7,
  18.8,
  19.5,
  20.3,
  20.5,
  19.9,
  18.2,
  18.4,
  19.3,
  19.3,
  20.3,
  19.6,
  20.0,
  18.9,
  19.8,
  21.0,
  20.8,
  18.1,
  17.5,
  20.6,
  20.8,
  18.5,
  20.1,
  18.9,
  19.6,
  18.6,
  20.8,
  18.5,
  19.0,
  19.1,
  18.2,
  20.9,
  20.9,
  21.1,
  19.5,
  19.7,
  19.7,
  16.6,
  18.3,
  17.9,
  18.8,
  19.0,
  19.8,
  20.1,
  19.7,
  17.7,
  18.7,
  19.8,
  19.0,
  17.5,
  18.7,
  18.3,
  18.4,
  19.0,
  17.6,
  17.9,
  19.1,
  18.1,
  18.7,
  19.0,
  17.9,
  20.2,
  17.8,
  17.6,
  17.9,
  20.3,
  21.3,
  22.2,
  20.8,
  20.3,
  20.3,
  22.2,
  21.1,
  18.3,
  20.3,
  20.3,
  19.3,
  19.7,
  20.8,
  19.0,
  19.2,
  20.4,
  18.9,
  20.1,
  20.5,
  21.0,
  20.5,
  20.3,
  18.3,
  18.5,
  19.2,
  19.7,
  19.7,
  19.6,
  20.4,
  20.9,
  20.8,
  21.6,
  21.6,
  20.5,
  20.9,
  20.5,
  19.8,
  20.5,
  20.0,
  21.0,
  21.2,
  20.8,
  22.2,
  21.8,
  21.2,
  20.5,
  22.9,
  21.7,
  20.9,
  21.0,
  22.0,
  21.9,
  21.1,
  21.3,
  21.5,
  21.4,
  20.4,
  16.6,
  19.1,
  21.0,
  23.0,
  21.9,
  20.4,
  21.4,
  20.9,
  21.1,
  20.5,
  20.6,
  18.9,
  21.4,
  21.7,
  18.7,
  19.2,
  20.1,
  21.1,
  21.5,
  22.2,
  21.1,
  21.2,
  22.2,
  21.2,
  20.8,
  21.2,
  22.7,
  21.5,
  20.3,
  19.6,
  20.9,
  20.8,
  21.2,
  20.1,
  21.3,
  21.2,
  17.6,
  20.7,
  21.8,
  22.6,
  18.3,
  20.5,
  18.7,
  19.7,
  19.7,
  20.0,
  18.8,
  19.0,
  19.8,
  19.6,
  20.0,
  20.5,
  18.9,
  18.6,
  18.0,
  17.6,
  19.3,
  20.3,
  20.8,
  21.1,
  20.5,
  18.6,
  19.1,
  20.8,
  21.3,
  21.9,
  22.2,
  22.5,
  20.3,
  20.0,
  20.4,
  19.6,
  19.3,
  23.1,
  21.7,
  21.7,
  21.6,
  20.9,
  20.5,
  20.5,
  20.8,
  21.5,
  23.7,
  19.8,
  20.6,
  21.3,
  21.1,
  21.9,
  21.8,
  20.1,
  18.7,
  19.4,
  18.6,
  21.7,
  22.3,
  21.4,
  18.4,
  19.5,
  18.3,
  20.0,
  21.6,
  20.2,
  20.6,
  21.2,
  21.8,
  22.2,
  22.1,
  21.5,
  21.3,
  21.7,
  21.1,
  21.5,
  22.4,
  22.0,
  21.8,
  21.8,
  20.8,
  21.2,
  21.3,
  20.2,
  19.1,
  20.7,
  19.7,
  21.6,
  20.3,
  21.6,
  23.1,
  22.5,
  22.5,
  22.5,
  23.0,
  21.9,
  20.8,
  19.8,
  18.8,
  18.0,
  20.1,
  19.1,
  19.6,
  18.4,
  19.7,
  19.2,
  20.8,
  21.8,
  20.4,
  21.0,
  18.4,
  19.6,
  20.2,
  20.2,
  21.3,
  20.1,
  20.3,
  21.3,
  19.9,
  19.2,
  19.2,
  19.0,
  18.9,
  18.6,
  19.9,
  20.8,
  20.7,
  20.5,
  19.1,
  19.6,
  18.6,
  20.1,
  20.1,
  20.1,
  19.5,
  21.1,
  17.2,
  19.9,
  19.9,
  19.3,
  19.2,
  20.3,
  21.6,
  20.9,
  20.3,
  19.8,
  20.0,
  18.9,
  21.3,
  18.9,
  20.3,
  19.6,
  19.1,
  19.8,
  19.9,
  17.9,
  19.9,
  19.1,
  19.9,
  21.3,
  21.5,
  22.2,
  21.3,
  21.3,
  20.6,
  20.4,
  21.3,
  20.6,
  19.8,
  19.7,
  20.0,
  18.7,
  20.1,
  18.2,
  20.8,
  19.9,
  20.5,
  19.2,
  19.3,
  20.4,
  17.4,
  19.8,
  17.4,
  19.7,
  18.1,
  20.5,
  18.6,
  19.8,
  19.2,
  19.3,
  18.8,
  19.9,
  17.9,
  19.3,
  18.3,
  19.0,
  18.9,
  19.6,
  18.6,
  15.2,
  19.6,
  19.2,
  19.1,
  19.1,
  19.4,
  19.4,
  19.6,
  18.0,
  18.2,
  18.3,
  18.6,
  18.6,
  18.6,
  17.8,
  18.1,
  17.4,
  19.4,
  18.3,
  17.4,
  18.8,
  18.7,
  18.5,
  19.2,
  19.9,
  19.1,
  19.0,
  17.0,
  18.1,
  18.6,
  18.5,
  18.3,
  20.8,
  17.6,
  17.7,
  20.3,
  18.7,
  18.3,
  18.4,
  18.0,
  16.9,
  17.5,
  16.4,
  16.5,
  17.0,
  17.9,
  18.5,
  17.7,
  17.3,
  18.2,
  18.5,
  16.1,
  17.6,
  18.1,
  18.1,
  17.9,
  18.2,
  19.0,
  16.7,
  18.5,
  18.9,
  18.5,
  18.8,
  18.8,
  19.0,
  17.6,
  19.6,
  19.4,
  18.4,
  18.8,
  20.1,
  19.8,
  19.4,
  18.8,
  18.1,
  19.6,
  20.1,
  18.8,
  18.4,
  17.2,
  19.0,
  17.9,
  19.6,
  16.8,
  18.2,
  18.4,
  19.3,
  19.3,
  20.2,
  19.5,
  20.4,
  20.0,
  19.2,
  19.6,
  20.8,
  17.2,
  16.2,
  18.0,
  18.6,
  18.7,
  22.5,
  20.6,
  18.9,
  19.3,
  18.6,
  18.3,
  18.1,
  18.5,
  18.6,
  19.5,
  19.8,
  18.6,
  19.2,
  20.1,
  19.3,
  19.2,
  18.5,
  20.1,
  21.4,
  19.4,
  20.0,
  19.5,
  20.6,
  21.8,
  19.9,
  18.8,
  19.9,
  19.0,
  19.9,
  18.1,
  19.3,
  18.8,
  19.4,
  19.1,
  19.3,
  19.7,
  19.3,
  20.6,
  19.4,
  18.0,
  19.2,
  19.1,
  19.3,
  19.6,
  18.9,
  17.0,
  19.7,
  19.6,
  18.2,
  18.3,
  19.0,
  20.0,
  19.9,
  20.8,
  20.4,
  19.5,
  19.9,
  19.3,
  20.6,
  19.5,
  19.9,
  20.1,
  18.5,
  20.0,
  20.6,
  21.7,
  21.9,
  21.7,
  18.8,
  21.9,
  22.7,
  21.4,
  20.6,
  21.8,
  22.5,
  21.1,
  19.9,
  18.5,
  18.3,
  20.6,
  20.9,
  20.6,
  20.1,
  20.5,
  21.8,
  20.9,
  20.0,
  20.5,
  20.2,
  20.7,
  20.2,
  20.7,
  19.4,
  19.8,
  18.7,
  20.3,
  18.9,
  17.4,
  19.3,
  19.0,
  19.4,
  19.6,
  19.6,
  19.7,
  18.9,
  19.8,
  20.1,
  21.4,
  21.3,
  20.9,
  22.1,
  21.8,
  20.9,
  20.5,
  22.1,
  21.5,
  20.4,
  20.3,
  21.0,
  20.7,
  19.8,
  20.0,
  19.8,
  20.8],
 'temperature_2m_min': [9.5,
  10.3,
  8.5,
  9.6,
  7.6,
  6.7,
  4.9,
  5.1,
  5.7,
  6.2,
  6.9,
  7.7,
  7.7,
  9.2,
  5.7,
  4.9,
  4.6,
  6.3,
  6.0,
  6.8,
  9.7,
  7.9,
  4.3,
  4.1,
  6.5,
  6.5,
  5.4,
  9.8,
  10.1,
  9.1,
  7.5,
  10.9,
  11.0,
  10.7,
  10.8,
  10.3,
  8.9,
  8.7,
  10.9,
  9.5,
  10.4,
  6.5,
  7.5,
  7.9,
  8.1,
  8.7,
  10.7,
  11.1,
  8.5,
  6.9,
  7.9,
  10.9,
  10.0,
  10.4,
  10.7,
  8.5,
  7.1,
  10.5,
  10.8,
  9.9,
  8.4,
  7.3,
  10.9,
  10.0,
  11.8,
  10.6,
  8.6,
  8.9,
  10.4,
  10.3,
  9.6,
  8.6,
  9.0,
  9.9,
  8.7,
  8.1,
  8.3,
  7.7,
  9.1,
  7.0,
  10.5,
  9.4,
  7.2,
  9.9,
  9.7,
  10.4,
  9.2,
  9.7,
  11.0,
  9.2,
  6.9,
  9.9,
  9.9,
  9.7,
  10.6,
  6.9,
  8.9,
  5.9,
  8.0,
  7.8,
  6.1,
  4.3,
  6.6,
  6.2,
  8.0,
  8.7,
  8.2,
  6.8,
  11.0,
  11.5,
  11.7,
  12.2,
  11.0,
  9.9,
  9.9,
  8.4,
  8.3,
  10.3,
  9.8,
  11.0,
  9.0,
  11.2,
  9.5,
  11.5,
  10.4,
  11.5,
  9.1,
  9.1,
  9.0,
  10.1,
  11.6,
  9.6,
  9.7,
  10.6,
  8.7,
  9.8,
  10.8,
  9.0,
  7.8,
  8.3,
  10.3,
  11.4,
  10.4,
  9.0,
  8.2,
  9.4,
  9.6,
  10.1,
  11.6,
  11.9,
  11.2,
  11.1,
  9.3,
  10.9,
  12.4,
  10.3,
  10.5,
  8.0,
  8.3,
  9.1,
  9.9,
  10.1,
  9.4,
  7.3,
  7.8,
  8.4,
  9.4,
  8.3,
  5.6,
  8.8,
  10.1,
  9.0,
  8.3,
  8.2,
  8.8,
  7.1,
  9.6,
  9.2,
  8.6,
  9.4,
  6.2,
  8.4,
  8.5,
  9.5,
  11.5,
  10.3,
  11.3,
  6.9,
  8.3,
  5.1,
  7.0,
  7.7,
  4.8,
  6.4,
  9.2,
  8.1,
  9.0,
  10.4,
  10.5,
  10.5,
  9.3,
  9.8,
  10.4,
  9.9,
  10.3,
  9.1,
  9.3,
  7.6,
  10.0,
  9.0,
  9.3,
  10.2,
  9.2,
  6.8,
  6.5,
  8.6,
  7.0,
  8.4,
  9.2,
  8.0,
  6.1,
  7.0,
  7.9,
  8.4,
  5.4,
  9.6,
  7.1,
  8.1,
  7.9,
  7.1,
  4.3,
  7.1,
  6.7,
  5.6,
  7.7,
  6.5,
  6.8,
  7.5,
  7.6,
  6.0,
  7.4,
  7.1,
  5.1,
  5.0,
  6.8,
  6.1,
  6.0,
  9.3,
  8.6,
  7.5,
  9.2,
  10.2,
  9.0,
  6.8,
  7.0,
  10.4,
  8.4,
  7.9,
  8.3,
  8.5,
  9.6,
  7.0,
  8.4,
  6.8,
  9.5,
  8.0,
  8.1,
  6.9,
  6.4,
  8.5,
  8.4,
  9.6,
  10.9,
  8.0,
  5.7,
  7.3,
  8.3,
  6.5,
  7.3,
  8.9,
  8.4,
  8.2,
  10.6,
  7.8,
  5.8,
  5.0,
  7.6,
  6.7,
  9.3,
  7.4,
  8.3,
  7.9,
  9.8,
  8.1,
  8.6,
  10.5,
  9.1,
  7.9,
  6.2,
  7.1,
  9.3,
  8.8,
  7.7,
  8.1,
  10.6,
  9.8,
  8.9,
  8.3,
  8.5,
  9.7,
  7.9,
  6.9,
  9.1,
  10.2,
  9.1,
  8.1,
  9.2,
  11.1,
  11.1,
  9.7,
  10.4,
  9.4,
  10.6,
  9.6,
  8.7,
  11.0,
  10.3,
  10.6,
  10.0,
  6.7,
  6.8,

#### Convertimos en API en un data frame

In [27]:
import pandas as pd

df_clima = pd.DataFrame(datos_json["daily"])

df_clima.head()

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,weather_code
0,2024-01-01,21.4,9.5,14.3,1.4,14.8,51
1,2024-01-02,22.1,10.3,14.7,0.2,13.7,51
2,2024-01-03,22.0,8.5,14.2,0.9,13.7,51
3,2024-01-04,21.9,9.6,14.1,0.1,15.5,51
4,2024-01-05,21.4,7.6,13.8,0.0,10.8,3

### Explicación columnas
#### time: fecha.
#### temperature_2m_max: temperatura máxima.
#### temperature_2m_min: temperatura mínima.
#### temperature_2m_mean: temperatura promedio.
#### precipitation_sum: precipitación diaria en milímetros.
#### wind_speed_10m_max: velocidad máxima del viento.
#### weather_code: código que representa la condición climática.

#### Dimensiones

In [28]:
df_clima.shape

(731, 7)

#### info del df

In [29]:
df_clima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 731 non-null    object
 1   temperature_2m_max   731 non-null    float64
 2   temperature_2m_min   731 non-null    float64
 3   temperature_2m_mean  731 non-null    float64
 4   precipitation_sum    731 non-null    float64
 5   wind_speed_10m_max   731 non-null    float64
 6   weather_code         731 non-null    int64
dtypes: float64(5), int64(1), object(1)
memory usage: 40.1+ KB

#### Descriptivas del df para ver que medidas podemos hacer antes de pasar a BI

In [30]:
df_clima.describe()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,weather_code
count,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000
mean,20.265253,9.097674,14.016142,3.925855,12.497811,50.941176
std,1.677726,1.615688,0.733867,5.215533,3.120554,15.853199
min,15.200000,3.900000,12.100000,0.000000,4.800000,2.000000
25%,19.100000,8.100000,13.500000,0.500000,10.300000,51.000000
50%,20.100000,9.300000,14.000000,1.500000,12.200000,51.000000
75%,21.350000,10.300000,14.500000,5.250000,14.300000,61.000000
max,26.200000,12.400000,16.300000,29.000000,22.300000,65.000000

#### Valores faltantes

In [31]:
df_clima.isna().sum()
# Inicialmente lo que podemos ver es que no existen valores faltantes en la base

time                   0
temperature_2m_max     0
temperature_2m_min     0
temperature_2m_mean    0
precipitation_sum      0
wind_speed_10m_max     0
weather_code           0
dtype: int64

#### Duplicados

In [32]:
df_clima.duplicated().sum() #Sin duplicados

0

In [33]:
df_clima['fecha_arr']=pd.to_datetime(df_clima['time'],errors='coerce') #Convertimos columna time a fecha
df_clima

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,weather_code,fecha_arr
0,2024-01-01,21.4,9.5,14.3,1.4,14.8,51,2024-01-01
1,2024-01-02,22.1,10.3,14.7,0.2,13.7,51,2024-01-02
2,2024-01-03,22.0,8.5,14.2,0.9,13.7,51,2024-01-03
3,2024-01-04,21.9,9.6,14.1,0.1,15.5,51,2024-01-04
4,2024-01-05,21.4,7.6,13.8,0.0,10.8,3,2024-01-05
...,...,...,...,...,...,...,...,...
726,2025-12-27,20.7,10.1,14.6,0.0,15.7,3,2025-12-27
727,2025-12-28,19.8,6.0,13.3,0.0,18.1,3,2025-12-28
728,2025-12-29,20.0,8.5,13.8,0.0,15.6,3,2025-12-29
729,2025-12-30,19.8,11.3,14.5,1.0,14.7,51,2025-12-30
730,2025-12-31,20.8,10.6,15.2,0.8,14.2,51,2025-12-31

In [34]:
df_clima.info() #Validamos que haya quedado convertida la nueva columna

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time                 731 non-null    object
 1   temperature_2m_max   731 non-null    float64
 2   temperature_2m_min   731 non-null    float64
 3   temperature_2m_mean  731 non-null    float64
 4   precipitation_sum    731 non-null    float64
 5   wind_speed_10m_max   731 non-null    float64
 6   weather_code         731 non-null    int64
 7   fecha_arr            731 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 45.8+ KB

In [35]:
df_clima['Ano']=df_clima['fecha_arr'].dt.year #Extraemos y creamos una columna de año
df_clima.head()

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,weather_code,fecha_arr,Ano
0,2024-01-01,21.4,9.5,14.3,1.4,14.8,51,2024-01-01,2024
1,2024-01-02,22.1,10.3,14.7,0.2,13.7,51,2024-01-02,2024
2,2024-01-03,22.0,8.5,14.2,0.9,13.7,51,2024-01-03,2024
3,2024-01-04,21.9,9.6,14.1,0.1,15.5,51,2024-01-04,2024
4,2024-01-05,21.4,7.6,13.8,0.0,10.8,3,2024-01-05,2024

In [36]:
# Creo una variable para categorizar los dias en su nombre

dias_espanol = {
    "Monday": "Lunes",
    "Tuesday": "Martes",
    "Wednesday": "Miércoles",
    "Thursday": "Jueves",
    "Friday": "Viernes",
    "Saturday": "Sábado",
    "Sunday": "Domingo"
}

df_clima["Dia_semana"] = (
    df_clima["fecha_arr"]
    .dt.day_name()
    .map(dias_espanol)
)
df_clima.head()

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,weather_code,fecha_arr,Ano,Dia_semana
0,2024-01-01,21.4,9.5,14.3,1.4,14.8,51,2024-01-01,2024,Lunes
1,2024-01-02,22.1,10.3,14.7,0.2,13.7,51,2024-01-02,2024,Martes
2,2024-01-03,22.0,8.5,14.2,0.9,13.7,51,2024-01-03,2024,Miércoles
3,2024-01-04,21.9,9.6,14.1,0.1,15.5,51,2024-01-04,2024,Jueves
4,2024-01-05,21.4,7.6,13.8,0.0,10.8,3,2024-01-05,2024,Viernes

In [37]:
# Creo variable tomando el supuesto y apoyandome en internet de que si la precipitación es 0 entonces no hay lluvia, si es mas de 0 si la hay
import numpy as np

df_clima["Tipo_dia"] = np.where(
    df_clima["precipitation_sum"] > 0,
    "Día lluvioso",
    "Día sin lluvia"
)
df_clima.head()

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,weather_code,fecha_arr,Ano,Dia_semana,Tipo_dia
0,2024-01-01,21.4,9.5,14.3,1.4,14.8,51,2024-01-01,2024,Lunes,Día lluvioso
1,2024-01-02,22.1,10.3,14.7,0.2,13.7,51,2024-01-02,2024,Martes,Día lluvioso
2,2024-01-03,22.0,8.5,14.2,0.9,13.7,51,2024-01-03,2024,Miércoles,Día lluvioso
3,2024-01-04,21.9,9.6,14.1,0.1,15.5,51,2024-01-04,2024,Jueves,Día lluvioso
4,2024-01-05,21.4,7.6,13.8,0.0,10.8,3,2024-01-05,2024,Viernes,Día sin lluvia

In [38]:
df_clima.groupby('Tipo_dia')['weather_code'].count().sort_values(ascending=False) 
# Vemos que hay días que en efector su precipitación fue 0 o no hubo lluvia

Tipo_dia
Día lluvioso      666
Día sin lluvia     65
Name: weather_code, dtype: int64

In [ ]:
# Exportamos para ir a trabajar en Power BI
# Dejo decimales en "," para que no me genere problemas en Power BI y separadores en ";"

df_clima.to_csv(
    r"C:\Users\piki_\Downloads\clima_bogota_2024_2025.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)